### ISSUE TITLE
sorting breaks if a value in the field being sorted is null

### ISSUE THREAD

**Issue by rickspencer3** [rapido-mobile/rapido-flutter#26]
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The method 'compareTo' was called on null.
Receiver: null
Tried calling: compareTo("5:21 PM")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DocumentList.sortByField.<anonymous closure> (package:rapido/src/document_list.dart:148:35)
#2      Sort._insertionSort (dart:_internal/sort.dart:69:36)
#3      Sort._doSort (dart:_internal/sort.dart:58:7)
#4      Sort.sort (dart:_internal/sort.dart:33:5)
#5      _ListBase&Object&ListMixin.sort (dart:collection/list.dart:339:10)
#6      DocumentList.sort (package:rapido/src/document_list.dart:138:16)
#7      DocumentList.sortByField (package:rapido/src/document_list.dart:148:7)
#8      _DocumentListSortButtonState.build.<anonymous closure> (package:rapido/src/document_list_sort_button.dart:32:16)
#9      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
#10     _RootZone.runUnary (dart:async/zone.d<…>

**Comment by rickspencer3** [comment]
fixed in commit e4980a6cbc7cc6d3303ff430dcb4d11fa679f71b
